---
- hosts: all
  become: yes
  become_user: root

  tasks:
    # Restart Nginx
  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
